# Generated by Django 3.1.1 on 2020-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Part Time'), ('Full Time', 'Part Time')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
