# Generated by Django 3.1.1 on 2020-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20200926_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('websit', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_leteer', models.TextField(max_length=500)),
            ],
        ),
    ]
