# Generated by Django 3.1.1 on 2020-09-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_apply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='onwer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='onwer_job', to='auth.user'),
            preserve_default=False,
        ),
    ]
